package graphical;

import org.jbox2d.common.Vec2;
import org.jbox2d.dynamics.Body;

import pbox2d.PBox2D;

public abstract class BallsyObject {

	protected Body _body;
	protected PBox2D _box2d;
	protected Level _level;
	
	public BallsyObject(PBox2D box2d, Level level){
		_box2d = box2d;
		_level = level;
	}
	
	/**
	 * Sets the underlying body of the object. This body represents
	 * the actual shape of the object and is generated by the physics engine
	 * after the BallsyObject has been instantiated. Therefore, a setter
	 * is required.
	 * @param body
	 */
	public void setBody(Body body){
		_body = body;
	}
	
	/**
	 * Should check to see if the object can be removed from the world.
	 */
	public abstract boolean done();
	
	/**
	 * Display the object using processing graphics.
	 */
	public abstract void display();
	
	/**
	 * Should add the BallsyObject to the logical (physics) world.
	 */
	public abstract void makeBody();	
	
	/**
	 * Should remove the BallsyObject entirely.
	 */
	public abstract void killBody();
	
	public int getPixelX(){
		return (int) _box2d.getBodyPixelCoord(_body).x;
	}
	
	public int getPixelY(){
		return (int) _box2d.getBodyPixelCoord(_body).y;
	}
	
	/**
	 * Applies a force given by the parameter to the object's 
	 * center of mass.
	 * @param vector
	 */
	public void applyForce(Vec2 vector){
		_body.applyForce(vector, _body.getWorldCenter());
	}
	
}
